name: ShopSphere API (Local)
values:
  - key: baseUrl
    value: 'http://localhost:5001/api/v1'
  - key: accessToken
    value: ''
  - key: userId
    value: ''
  - key: productId
    value: ''
  - key: productSlug
    value: ''
  - key: categoryId
    value: ''
  - key: variantId
    value: ''
  - key: warehouseId
    value: ''
  - key: inventoryId
    value: ''
  - key: movementId
    value: ''
  - key: reservationId
    value: ''
  - key: cartId
    value: ''
  - key: guestSessionId
    value: ''
  - key: checkoutId
    value: ''
  - key: checkoutVersion
    value: '1'
  - key: paymentId
    value: ''
  - key: paymentIntentId
    value: ''
  - key: orderId
    value: ''
  - key: orderNumber
    value: ''
  - key: guestAccessToken
    value: ''
